// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/erigontech/erigon-lib/state (interfaces: CanonicalsReader)
//
// Generated by this command:
//
//	mockgen -typed=true -destination=./iters_mock.go -package=state . CanonicalsReader
//

// Package state is a generated GoMock package.
package state

import (
	reflect "reflect"

	kv "github.com/erigontech/erigon-lib/kv"
	order "github.com/erigontech/erigon-lib/kv/order"
	stream "github.com/erigontech/erigon-lib/kv/stream"
	gomock "go.uber.org/mock/gomock"
)

// MockCanonicalsReader is a mock of CanonicalsReader interface.
type MockCanonicalsReader struct {
	ctrl     *gomock.Controller
	recorder *MockCanonicalsReaderMockRecorder
}

// MockCanonicalsReaderMockRecorder is the mock recorder for MockCanonicalsReader.
type MockCanonicalsReaderMockRecorder struct {
	mock *MockCanonicalsReader
}

// NewMockCanonicalsReader creates a new mock instance.
func NewMockCanonicalsReader(ctrl *gomock.Controller) *MockCanonicalsReader {
	mock := &MockCanonicalsReader{ctrl: ctrl}
	mock.recorder = &MockCanonicalsReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCanonicalsReader) EXPECT() *MockCanonicalsReaderMockRecorder {
	return m.recorder
}

// TxNum2ID mocks base method.
func (m *MockCanonicalsReader) TxNum2ID(arg0 kv.Tx, arg1 uint64) (uint64, kv.TxnId, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TxNum2ID", arg0, arg1)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(kv.TxnId)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// TxNum2ID indicates an expected call of TxNum2ID.
func (mr *MockCanonicalsReaderMockRecorder) TxNum2ID(arg0, arg1 any) *MockCanonicalsReaderTxNum2IDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxNum2ID", reflect.TypeOf((*MockCanonicalsReader)(nil).TxNum2ID), arg0, arg1)
	return &MockCanonicalsReaderTxNum2IDCall{Call: call}
}

// MockCanonicalsReaderTxNum2IDCall wrap *gomock.Call
type MockCanonicalsReaderTxNum2IDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCanonicalsReaderTxNum2IDCall) Return(arg0 uint64, arg1 kv.TxnId, arg2 bool, arg3 error) *MockCanonicalsReaderTxNum2IDCall {
	c.Call = c.Call.Return(arg0, arg1, arg2, arg3)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCanonicalsReaderTxNum2IDCall) Do(f func(kv.Tx, uint64) (uint64, kv.TxnId, bool, error)) *MockCanonicalsReaderTxNum2IDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCanonicalsReaderTxNum2IDCall) DoAndReturn(f func(kv.Tx, uint64) (uint64, kv.TxnId, bool, error)) *MockCanonicalsReaderTxNum2IDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TxnIdsOfCanonicalBlocks mocks base method.
func (m *MockCanonicalsReader) TxnIdsOfCanonicalBlocks(arg0 kv.Tx, arg1, arg2 int, arg3 order.By, arg4 int) (stream.U64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TxnIdsOfCanonicalBlocks", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(stream.U64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TxnIdsOfCanonicalBlocks indicates an expected call of TxnIdsOfCanonicalBlocks.
func (mr *MockCanonicalsReaderMockRecorder) TxnIdsOfCanonicalBlocks(arg0, arg1, arg2, arg3, arg4 any) *MockCanonicalsReaderTxnIdsOfCanonicalBlocksCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxnIdsOfCanonicalBlocks", reflect.TypeOf((*MockCanonicalsReader)(nil).TxnIdsOfCanonicalBlocks), arg0, arg1, arg2, arg3, arg4)
	return &MockCanonicalsReaderTxnIdsOfCanonicalBlocksCall{Call: call}
}

// MockCanonicalsReaderTxnIdsOfCanonicalBlocksCall wrap *gomock.Call
type MockCanonicalsReaderTxnIdsOfCanonicalBlocksCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCanonicalsReaderTxnIdsOfCanonicalBlocksCall) Return(arg0 stream.U64, arg1 error) *MockCanonicalsReaderTxnIdsOfCanonicalBlocksCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCanonicalsReaderTxnIdsOfCanonicalBlocksCall) Do(f func(kv.Tx, int, int, order.By, int) (stream.U64, error)) *MockCanonicalsReaderTxnIdsOfCanonicalBlocksCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCanonicalsReaderTxnIdsOfCanonicalBlocksCall) DoAndReturn(f func(kv.Tx, int, int, order.By, int) (stream.U64, error)) *MockCanonicalsReaderTxnIdsOfCanonicalBlocksCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
